version: '3.7'

services:
    
    web:
        build:
            context: ./services/web 
            dockerfile: Dockerfile
        entrypoint: ['/usr/src/app/entrypoint.sh']
        volumes:
            - './services/web:/usr/src/app'
        ports:
            - 5001:5000
        environment: 
            - FLASK_ENV=development
            - APP_SETTINGS=application.config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:postgres@database:5432/drills_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@database:5432/drills_test
        depends_on:
            - database

    database:
        build:
            context: ./services/web/application/db
            dockerfile: Dockerfile
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres